---
database:
    backend: mysql
    username: root
    password: toor
    ip: localhost
    class: Database

web:
    rest: on
    html:
        engine: mustache
        search: "templates/"
    https: force
    session:
        class: Session
